all:
  vars:
    env: production
prod:
  hosts:
    client1:
      ansible_host: 192.168.99.171
    client2:
      ansible_host: 192.168.99.172
master:
  hosts:
    master:
      ansible_host: 192.168.99.170