all:
  vars:
    env: production
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
prod:
  hosts:
    client1:
      ansible_host: 192.168.99.171

master:
  hosts:
    master-node:
      ansible_host: 192.168.99.170
