---

- name : "Installation de Docker sur les workers"
  hosts: worker
  become: yes
  gather_facts: yes
  vars_files:
    - /home/MyUser/send/ansible/EAZY/TP5/webapp/group_vars

  pre_tasks:
    - name: INSTALL PYTHON FOR DOCKER
      pip:
        name: docker-py
  tasks:
    - name: Installation de docker
      command:
        cmd: "{{ item }}"
      with_items:
      - curl -fsSL https://get.docker.com -o install-docker.sh
      - sh install-docker.sh

    - name: Add user MyUser to docker group
      user:
        name: MyUser
        groups: docker
        append: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
    - name: Create volumes
      community.docker.docker_volume:
        name: myvolume

    - name: DEPLOY CONTAINER
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ container_image }}"
        restart: true
        state: started
        detach: yes
        ports:
          - "{{ container_port_exposed }}"

    - name: Copy file on the remote machine for editing
      ansible.builtin.copy:
        src: "{{ src_folder_local_host }}"
        dest: "{{ dest_folder_remote_host }}"

    - name: Copy local files to container
      ansible.builtin.shell:
        cmd: docker cp "{{ dest_folder_remote_host }}""{{ public_folder }}" "{{ container_name }}":"{{ dest_folder_container }}"




