all:
  vars:
    env: production
    # ansible_python_interpreter: "/usr/bin/python3"
worker:
  hosts:
    ansible-worker1:
      ansible_host: 192.168.1.171

master:
  hosts:
    ansible-master:
      ansible_host: 192.168.1.170
