---
- name: Apache installation using docker
  hosts: prod
  become: true
  pre_tasks:
    - name: Install docker python
      pip:
        name: docker-py
  tasks:
    - name: Installation de docker
      command:
        cmd: "{{ item }}"
      with_items:
      - curl -fsSL https://get.docker.com -o install-docker.sh
      - sh install-docker.sh

    - name: Add user cool to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

